spring:
  application:
    name: tw-backend
  spring:
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=tailorsWorkshop;integratedSecurity=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create / create-drop / update / validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
