spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TailorsWorkshopDB;encrypt=false;trustServerCertificate=true
    username: djix
    password: 88888888
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: trueS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

