spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TailorsWorkshopDB;encrypt=false;trustServerCertificate=true
    username: djix
    password: 88888888
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create  # create / create-drop / update / validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  main:
    allow-bean-definition-overriding: true
cors:
  allowed-origin: http://localhost:5173


